"""change comfort model

Revision ID: 0dc33496bf68
Revises: 0077fb2ee03a
Create Date: 2025-06-15 18:55:58.779305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dc33496bf68"
down_revision: Union[str, None] = "0077fb2ee03a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rooms_facilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("facility_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    
    # Исправленный порядок удаления таблиц
    op.add_column("rooms", sa.Column("description", sa.String(), nullable=True))
    
    # 1. Добавляем колонку как NULLABLE
    op.add_column("rooms", sa.Column("quantity", sa.Integer(), nullable=True))
    
    # 2. Заполняем существующие записи значением по умолчанию
    op.execute("UPDATE rooms SET quantity = 1 WHERE quantity IS NULL")
    
    # 3. Меняем колонку на NOT NULL
    op.alter_column("rooms", "quantity", nullable=False)
    
    op.drop_column("rooms", "discription")
    op.drop_column("rooms", "count")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms", sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "rooms",
        sa.Column("discription", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("rooms", "quantity")
    op.drop_column("rooms", "description")
    
    # Восстановление таблиц в правильном порядке
    op.create_table(
        "comfort",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="comfort_pkey"),
    )
    op.create_table(
        "rooms_comfort",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("rooms_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("comfort_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["comfort_id"], ["comfort.id"], name="rooms_comfort_comfort_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["rooms_id"], ["rooms.id"], name="rooms_comfort_rooms_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="rooms_comfort_pkey"),
    )
    
    op.drop_table("rooms_facilities")
    op.drop_table("facilities")
