"""add extend_existing

Revision ID: f375ee33caae
Revises: 4e660181faaf
Create Date: 2025-10-02 19:37:14.263527

"""

from typing import Sequence, Union




# revision identifiers, used by Alembic.
revision: str = "f375ee33caae"
down_revision: Union[str, None] = "4e660181faaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
